"""Update Assessment model with new enums and string fields

Revision ID: 469a81334c6a
Revises: 1e694734fd2c
Create Date: 2025-10-13 08:55:22.213794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '469a81334c6a'
down_revision: Union[str, Sequence[str], None] = '1e694734fd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('original_id', sa.String(), nullable=True))
    op.alter_column('assessments', 'conjunctivitis',
               existing_type=postgresql.ENUM('presente', 'ausente', name='presenceabsence'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assessments', 'skin_lesion',
               existing_type=postgresql.ENUM('presente', 'ausente', name='presenceabsence'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'skin_lesion',
               existing_type=sa.String(),
               type_=postgresql.ENUM('presente', 'ausente', name='presenceabsence'),
               existing_nullable=True)
    op.alter_column('assessments', 'conjunctivitis',
               existing_type=sa.String(),
               type_=postgresql.ENUM('presente', 'ausente', name='presenceabsence'),
               existing_nullable=True)
    op.drop_column('assessments', 'original_id')
    # ### end Alembic commands ###
