"""Set default value of is_active to False for users

Revision ID: b2466947b8b8
Revises: fe8353f6c31b
Create Date: 2025-10-14 00:25:53.942238

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b2466947b8b8"
down_revision: Union[str, Sequence[str], None] = "fe8353f6c31b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
