"""Add full_name and institution to User model

Revision ID: fe8353f6c31b
Revises: 469a81334c6a
Create Date: 2025-10-13 10:26:37.816644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe8353f6c31b"
down_revision: Union[str, Sequence[str], None] = "469a81334c6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=False))
    op.add_column(
        "users", sa.Column("institution", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "institution")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
